version: '3.8'

services:
  gateway:
    build:
      context: ./gateway
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=gateway.settings
    depends_on:
      - auth_service
      - crud_service

  auth_service:
    build:
      context: ./auth_service
    ports:
      - "8001:8001"
    environment:
      - DJANGO_SETTINGS_MODULE=auth_service.settings
    depends_on:
      - mongo

  crud_service:
    build:
      context: ./crud_service
    ports:
      - "8002:8002"
    environment:
      - DJANGO_SETTINGS_MODULE=crud_service.settings
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
