services:

  gateway:
    build:
      context: ${ROUTE_GATEWAY}
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    depends_on:
      - ${MSSESSIONS_HOST}

    environment:
      - MONGODB_URI=${MONGODB_URI}

  ms-sessions:
    build:
      context: ./${MSSESSIONS_HOST}
    ports:
      - "${MSSESSIONS_PORT}:${MSSESSIONS_PORT}"
    environment:
      - MONGODB_URI=${MONGODB_URI}

  ms-products:
    build:
      context: ./${MSPRODUCTS_HOST}
    ports:
      - "${MSPRODUCTS_PORT}:${MSPRODUCTS_PORT}"
    environment:
      - MONGODB_URI=${MONGODB_URI}

volumes:
  mongo-data:
    driver: local
